
version: '3.8'

services:
  db:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             gunicorn trading_card_project.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    depends_on:
      - db
    restart: unless-stopped

volumes:
  static_volume:
  media_volume: 
