# Generated by Django 5.2.1 on 2025-05-24 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "rarity",
                    models.CharField(choices=[("common", "Common")], max_length=20),
                ),
                ("image", models.ImageField(upload_to="cards/")),
                ("description", models.TextField()),
            ],
        ),
    ]
